### ISSUE TITLE
Unable to install on Ubuntu 12.04

### ISSUE THREAD

**Issue by garagatyi** [wlaurance/slack-for-linux#28]
Tried install this client on Ubuntu 12.04 with 
```
npm install npm@latest -g
npm install slack-for-linux -g
```
But installation failed, here is logs:
https://gist.github.com/garagatyi/3b91b3534751e2a423eb

**Comment by twolfson** [comment]
It looks like you are running `node@0.9` which is causing compatibility issues with some of our dependencies. Can you switch over to `node@0.10` and try again?

Since you are running `nvm`, this can be done via:

```bash
nvm install 0.10
nvm use 0.10
```

I will open a PR to update our `package.json` to restrict on `node@0.10` to reduce the likelihood of having this issue.

**Comment by twolfson** [comment]
I have opened #29 to add the warning notice. However, tehcnically this issue independent from the warning notice so I am going to close it.

**Comment by garagatyi** [comment]
@twolfson Thanks, I'm not node guy at all. I've reinstall node completely and now it works.
