### ISSUE TITLE
Can't watch Youtube video in preview 

### ISSUE THREAD

**Issue by garagatyi** [wlaurance/slack-for-linux#32]
Slack has cool feature - preview youtube videos without leaving the chat window. 
Slack-for-linux currently show just open in external browser button. Can you add play button as well?

**Comment by twolfson** [comment]
This is probably due to Flash being disabled by default in `nw.js`. It should be fixed if we add the `plugin: true` flag.

https://github.com/nwjs/nw.js/wiki/Third-party-browser-plugins

I will take a look at adding it by the end of next weekend. If someone wants to do it before then, please leave a comment.

**Comment by twolfson** [comment]
Yep, the fix was as simple as that. I opened PR #33 to fix this.

**Comment by garagatyi** [comment]
Nice!

**Comment by garagatyi** [comment]
Can html5 be used instead of flash?

**Comment by twolfson** [comment]
HTML5 video should be enabled by default so I doubt that's the issue but I don't have a conclusion answer. Slack could be looking for a proprietary codec like H264 but I doubt it.
